### ISSUE TITLE
summary statistics in observed data

### ISSUE THREAD

**Issue by gsilvaarias** [c70smith/ABCvalidation#1]
Dear Chris,
many thanks for this great update for the msABC software. Congratulations for the nice job and the publication. 
There is a couple of details that seem to be lacking in the code you are providing comparing to previous versions of msABC. The output of the polymorphism data in the file _tempoutput_ms.txt_ and the option to calculate the summary statistics for observed data using the _--obs_ option. 
Comparing your code with [idaios/msABC](https://github.com/idaios/msABC), I was able to recover the _tempoutput_ms.txt_ output just adding `tempdatafile = fopen("tempoutput_ms.txt", "w");` after the line 513 in the _ms.c_ file. But I had no success with the summary statistics for the observed data. When tried I got in the output three seed numbers and _Segmentation fault (core dumped)_ message.
It would be nice if you can check this issue and activate the option to get the summary stats for the observed data. From my point of view, this option is one of the better features of msABC since it allows to get the summary stats for both the observed and simulated data with exactly the same code.
Thanks!
Gustavo

**Comment by chriscrsmith** [comment]
Hi Gustavo, 

Thank you for the message. Just now I cloned the git repo, re-compiled the software, ran the code, and it works for me. I used “--poldata tempPolOut.txt” (with two dashes “-“) to output the polymorphism data. And to calculate stats on the observed data, I used “msABC numSequences numSims -I numPops n1 n2 --frag-begin --finp locfile --frag-end --obs tempPolOut.txt”.

Will you please check to see if this works for you? 

Thank you!
chris

**Comment by gsilvaarias** [comment]
Hi Chris,
thanks for the reply.
The commands are working fine. Thank you.
Just a small detail. The script fas2ms.pl provided in the msABC package (that converts fasta or nexus alignments to ms format to calculate the sumstas of observed data with msABC) output the positions of the segregating sites in _tab_ delimited format. Using this file as input produces an error because msABC expects a _space_ delimited format for this especific line. It can be easily fixed changing either the perl script or the ms.c code. I did it on the fas2ms.pl (see the atachment).
[fas2ms.zip](https://github.com/chriscrsmith/ABCvalidation/files/3645806/fas2ms.zip)

Best,
Gustavo

**Comment by chriscrsmith** [comment]
Thanks, Gustavo
